export const KEYWORD_CATEGORIES = {

    "Literatur": "literatur_oberkategorie",
    "Sophie von La Roches Werke": "literatur",
    "Schaffensprozess": "literatur",
    "Inhalt eigener Werke": "literatur",
    "Rezeption eigener Werke": "literatur",
    "Schriftstellerische Tätigkeit als Frau": "literatur",
    "Johann Isaak von Gernings Werke": "literatur",
    "Johann Isaak von Gernings Dichtung": "literatur",
    "Rezeption anderer Werke": "literatur",
    "Kulturgeschichtliches Buch": "literatur",
    "Dichtung": "literatur",
    "Biographisches Werk": "literatur",
    "Brief": "literatur",
    "Philosophischer Text": "literatur",
    "Kunst": "literatur",

    "Geselligkeit/Beziehungen": "beziehungen_oberkategorie",
    "Freundschaft": "beziehungen",
    "Freundschaft mit Wieland": "beziehungen",
    "Familie": "beziehungen",
    "Sophie von La Roches Kinder": "beziehungen",
    "Sophie von La Roches Enkel*innen": "beziehungen",
    "Johann Isaak von Gernings Mutter": "beziehungen",
    "Schriftsteller-/Dichterkreis": "beziehungen",
    "Weimarer Viergestirn (Goethe, Schiller, Herder, Wieland)": "beziehungen",
    "Liebesbeziehung": "beziehungen",
    "Verliebtheit Gernings": "beziehungen",
    "Bekanntschaften": "beziehungen",

    "Persönliches": "persoenliches_oberkategorie",
    "Alter": "persoenliches",
    "Krankheit": "persoenliches",
    "Haus und Garten": "persoenliches",
    "Personal/Dienstleister": "persoenliches",
    "Geschäfte/Verkauf": "persoenliches",

    "Politik": "politik_oberkategorie",
    "Deutschland (Politik)": "politik",
    "Innenpolitische Unruhe": "politik",
    "Revolution": "politik",
    "Frankreich (Politik)": "politik",
    "Italien (Politik)": "politik",
    "Deutschland - Frankreich": "politik",
    "Koalitionskriege": "politik",
 
    "Reisen": "reisen_oberkategorie",
    "Deutschland (Reisen)": "reisen",
    "Taunus": "reisen",
    "Italien (Reisen)": "reisen",
    "Natur": "reisen",
    "Ausflug": "reisen",

    "Emotion": "emotion_oberkategorie",
    "Freude": "emotion",
    "Trauer": "emotion",
    "Trübsinnigkeit": "emotion",
    "Missbilligung": "emotion",
    "Streit": "emotion",

    "Sprechakt": "sprechakt_oberkategorie",
    "Wunsch": "sprechakt",
    "Appell": "sprechakt",
    "Dank": "sprechakt",
    "Lob": "sprechakt",
    "Warnung": "sprechakt",
    "Kondolenz": "sprechakt",
    "Ratschlag": "sprechakt",
    "Empfehlung": "sprechakt",
    "Bitte": "sprechakt",
    "Bitte um Besorgung": "sprechakt",
    "Bitte um Besorgung von Büchern": "sprechakt",
    "Bitte um Weitersendung von Büchern": "sprechakt",
    "Bitte um Weitersendung von Briefen": "sprechakt",

    "Ästhetischer Sprachgebrauch": "aesthetik_oberkategorie",
    "Antike griechische Schriftsteller": "antikeGriechen_oberkategorie",
    "Erziehung": "erziehung_oberkategorie",
    "Religion": "religion_oberkategorie",

    "Warensendung": "warensendung_oberkategorie",
    "Warensendung Literatur": "warensendung",
    "Rückgabe geliehener Literatur": "warensendung",
    "Sendung Brief": "warensendung",
    "Rücksendung Brief": "warensendung",

    "Zitat": "zitat_oberkategorie",
    "Zitat Gedicht": "zitat",
    "Zitat philosophischer Text": "zitat"

};

export const ALL_KEYWORDS = Object.keys(KEYWORD_CATEGORIES);
